//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIENNAMPOSTWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddressTemp
    {
        public string Id { get; set; }
        public string Name { get; set; }
        public string Phone { get; set; }
        public string AddressInfo { get; set; }
        public string ProvinceId { get; set; }
        public string DistrictId { get; set; }
        public string WardId { get; set; }
    }
}
