//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIENNAMPOSTWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_Customers
    {
        public string CustomerID { get; set; }
        public string CustomerCode { get; set; }
        public string CustomerName { get; set; }
        public string CustomerGroupID { get; set; }
        public string Address { get; set; }
        public string DistrictID { get; set; }
        public string ProvinceID { get; set; }
        public string CountryID { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public bool IsActive { get; set; }
        public string PostOfficeID { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string WardID { get; set; }
        public string UserLogin { get; set; }
        public string Deputy { get; set; }
        public string ClientUser { get; set; }
    }
}
