//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIENNAMPOSTWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_Provinces
    {
        public string ProvinceID { get; set; }
        public string ProvinceName { get; set; }
        public string CountryID { get; set; }
        public string ZoneID { get; set; }
        public string ProvinceCode { get; set; }
    }
}
