//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIENNAMPOSTWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_Services
    {
        public string ServiceID { get; set; }
        public string ServiceName { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
