//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MIENNAMPOSTWEB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BS_Wards
    {
        public string WardID { get; set; }
        public string WardName { get; set; }
        public string DistrictID { get; set; }
    }
}
